export const initialAppointments = [
  {
    id: "appt-2041",
    name: "Maya Thompson",
    email: "maya.thompson@nimblelabs.com",
    phone: "+1 (415) 555-0138",
    company: "Nimble Labs",
    title: "Product demo",
    date: "Aug 20, 2026",
    time: "2:30 PM",
    timezone: "PDT (UTC−7)",
    duration: "30 min",
    host: "Shahtaz",
    source: "WhatsApp",
    status: "Confirmed",
    location: "Google Meet",
    notes: "Interested in SSO, team permissions, and annual pricing for a 70-person support team.",
    booked: "Today · 10:47 AM",
  },
  {
    id: "appt-2040",
    name: "Daniel Kim",
    email: "daniel@northstar.io",
    phone: "+1 (647) 555-0192",
    company: "Northstar",
    title: "Sales consultation",
    date: "Aug 20, 2026",
    time: "4:00 PM",
    timezone: "EDT (UTC−4)",
    duration: "45 min",
    host: "John Carter",
    source: "Website",
    status: "Confirmed",
    location: "Google Meet",
    notes: "Wants to compare Growth and Business plans before the next budget cycle.",
    booked: "Today · 9:22 AM",
  },
  {
    id: "appt-2038",
    name: "Sofia Martins",
    email: "sofia@lumon.pt",
    phone: "+351 912 345 678",
    company: "Lumon Studio",
    title: "Onboarding call",
    date: "Aug 21, 2026",
    time: "10:00 AM",
    timezone: "WEST (UTC+1)",
    duration: "30 min",
    host: "Jane Cooper",
    source: "Instagram",
    status: "Pending",
    location: "Google Meet",
    notes: "Needs help inviting teammates and configuring the website widget.",
    booked: "Yesterday · 6:18 PM",
  },
  {
    id: "appt-2034",
    name: "Aisha Rahman",
    email: "aisha@orbit.com.bd",
    phone: "+880 1711 000000",
    company: "Orbit Commerce",
    title: "Product demo",
    date: "Aug 23, 2026",
    time: "11:30 AM",
    timezone: "BST (UTC+6)",
    duration: "30 min",
    host: "Shahtaz",
    source: "Website",
    status: "Confirmed",
    location: "Google Meet",
    notes: "High-volume WhatsApp support use case. Asked about peak-season capacity.",
    booked: "Aug 18 · 3:31 PM",
  },
  {
    id: "appt-2029",
    name: "Noah Williams",
    email: "noah.w@ember.co.uk",
    phone: "+44 7700 900128",
    company: "Ember Retail",
    title: "Sales consultation",
    date: "Aug 19, 2026",
    time: "3:00 PM",
    timezone: "BST (UTC+1)",
    duration: "45 min",
    host: "John Carter",
    source: "Facebook",
    status: "Completed",
    location: "Google Meet",
    notes: "Discussed refund workflows and approval routing.",
    booked: "Aug 17 · 1:04 PM",
  },
  {
    id: "appt-2025",
    name: "Liam Chen",
    email: "liam@papertrail.sg",
    phone: "Not collected",
    company: "Papertrail",
    title: "Product demo",
    date: "Aug 18, 2026",
    time: "9:00 AM",
    timezone: "SGT (UTC+8)",
    duration: "30 min",
    host: "Shahtaz",
    source: "Website",
    status: "Cancelled",
    location: "Google Meet",
    notes: "Cancelled by visitor two hours before the call.",
    booked: "Aug 16 · 5:42 PM",
  },
];

export const initialSchedule = [
  { id: "monday", day: "Monday", enabled: true, start: "09:00 AM", end: "05:00 PM" },
  { id: "tuesday", day: "Tuesday", enabled: true, start: "09:00 AM", end: "05:00 PM" },
  { id: "wednesday", day: "Wednesday", enabled: true, start: "09:00 AM", end: "05:00 PM" },
  { id: "thursday", day: "Thursday", enabled: true, start: "09:00 AM", end: "05:00 PM" },
  { id: "friday", day: "Friday", enabled: true, start: "09:00 AM", end: "03:00 PM" },
  { id: "saturday", day: "Saturday", enabled: false, start: "10:00 AM", end: "02:00 PM" },
  { id: "sunday", day: "Sunday", enabled: false, start: "10:00 AM", end: "02:00 PM" },
];

export const initialBookingFields = [
  { id: "name", label: "Full name", type: "Text", enabled: true, required: true, locked: true },
  { id: "email", label: "Email address", type: "Email", enabled: true, required: true, locked: true },
  { id: "phone", label: "Phone number", type: "Phone", enabled: true, required: false },
  { id: "company", label: "Company", type: "Text", enabled: true, required: false },
  { id: "topic", label: "What would you like to discuss?", type: "Long text", enabled: true, required: true },
];
