export const initialLeads = [
  {
    id: "lead-1086",
    name: "Maya Thompson",
    email: "maya.thompson@nimblelabs.com",
    phone: "+1 (415) 555-0138",
    company: "Nimble Labs",
    role: "Head of Support",
    source: "WhatsApp",
    score: 92,
    quality: "Hot",
    status: "Qualified",
    owner: "Shahtaz",
    captured: "Today · 10:47 AM",
    session: "#4821",
    location: "San Francisco, CA",
    intent: "Enterprise plan",
    summary: "Evaluating support automation for a 70-person team and asked about SSO, onboarding, and annual pricing.",
    fields: { "Team size": "51–100", Budget: "$10k–$25k", Timeline: "This quarter" },
    activity: [["Lead qualified by Atlas AI", "10:47 AM"], ["Email and phone collected", "10:45 AM"], ["Conversation started on WhatsApp", "10:39 AM"]],
  },
  {
    id: "lead-1085",
    name: "Daniel Kim",
    email: "daniel@northstar.io",
    phone: "+1 (647) 555-0192",
    company: "Northstar",
    role: "Operations Manager",
    source: "Website",
    score: 78,
    quality: "Warm",
    status: "New",
    owner: "Unassigned",
    captured: "Today · 10:33 AM",
    session: "#4819",
    location: "Toronto, Canada",
    intent: "Pricing enquiry",
    summary: "Comparing plans for a growing support team and requested details about SSO availability.",
    fields: { "Team size": "51–100", Budget: "Not provided", Timeline: "1–3 months" },
    activity: [["Lead created from web chat", "10:33 AM"], ["Work email collected", "10:32 AM"]],
  },
  {
    id: "lead-1083",
    name: "Sofia Martins",
    email: "sofia@lumon.pt",
    phone: "+351 912 345 678",
    company: "Lumon Studio",
    role: "Founder",
    source: "Instagram",
    score: 64,
    quality: "Warm",
    status: "Contacted",
    owner: "Jane Cooper",
    captured: "Today · 9:18 AM",
    session: "#4816",
    location: "Lisbon, Portugal",
    intent: "Team access",
    summary: "Interested in adding teammates to a Starter account and may upgrade as the studio grows.",
    fields: { "Team size": "6–10", Budget: "Under $5k", Timeline: "Exploring" },
    activity: [["Assigned to Jane Cooper", "9:42 AM"], ["Lead captured from Instagram", "9:18 AM"]],
  },
  {
    id: "lead-1080",
    name: "Noah Williams",
    email: "noah.w@ember.co.uk",
    phone: "+44 7700 900128",
    company: "Ember Retail",
    role: "CX Lead",
    source: "Facebook",
    score: 48,
    quality: "Cool",
    status: "New",
    owner: "Unassigned",
    captured: "Yesterday · 6:42 PM",
    session: "#4803",
    location: "London, United Kingdom",
    intent: "Refund workflow",
    summary: "Asked how Argon handles refund requests and whether a human approval step can be required.",
    fields: { "Team size": "11–25", Budget: "Not provided", Timeline: "Exploring" },
    activity: [["Lead captured from Facebook", "Yesterday · 6:42 PM"]],
  },
  {
    id: "lead-1078",
    name: "Aisha Rahman",
    email: "aisha@orbit.com.bd",
    phone: "+880 1711 000000",
    company: "Orbit Commerce",
    role: "Product Manager",
    source: "Website",
    score: 85,
    quality: "Hot",
    status: "Qualified",
    owner: "John Carter",
    captured: "Yesterday · 3:27 PM",
    session: "#4797",
    location: "Dhaka, Bangladesh",
    intent: "WhatsApp automation",
    summary: "Looking to automate WhatsApp support for a high-volume commerce operation before peak season.",
    fields: { "Team size": "26–50", Budget: "$5k–$10k", Timeline: "Within 30 days" },
    activity: [["Qualified by John Carter", "Yesterday · 4:02 PM"], ["Demo requested", "Yesterday · 3:31 PM"], ["Lead captured from website", "Yesterday · 3:27 PM"]],
  },
  {
    id: "lead-1072",
    name: "Liam Chen",
    email: "liam@papertrail.sg",
    phone: "Not collected",
    company: "Papertrail",
    role: "Growth Associate",
    source: "Website",
    score: 31,
    quality: "Cool",
    status: "Disqualified",
    owner: "Shahtaz",
    captured: "Aug 18 · 11:04 AM",
    session: "#4762",
    location: "Singapore",
    intent: "General research",
    summary: "Early research with no defined implementation timeline or budget.",
    fields: { "Team size": "1–5", Budget: "Not provided", Timeline: "No timeline" },
    activity: [["Marked as disqualified", "Aug 18 · 2:11 PM"], ["Lead captured from website", "Aug 18 · 11:04 AM"]],
  },
];

export const initialCaptureFields = [
  { id: "field-name", label: "Full name", type: "Text", enabled: true, required: true, locked: true },
  { id: "field-email", label: "Email address", type: "Email", enabled: true, required: true, locked: true },
  { id: "field-phone", label: "Phone number", type: "Phone", enabled: true, required: false },
  { id: "field-company", label: "Company", type: "Text", enabled: true, required: false },
  { id: "field-role", label: "Job title", type: "Text", enabled: true, required: false },
  { id: "field-team", label: "Team size", type: "Dropdown", enabled: true, required: false },
  { id: "field-budget", label: "Budget range", type: "Dropdown", enabled: false, required: false },
];

export const sourcePerformance = [
  { source: "Website", leads: 148, qualified: 43, conversion: 29, color: "bg-sky-500" },
  { source: "WhatsApp", leads: 72, qualified: 31, conversion: 43, color: "bg-emerald-500" },
  { source: "Instagram", leads: 41, qualified: 9, conversion: 22, color: "bg-fuchsia-500" },
  { source: "Facebook", leads: 25, qualified: 5, conversion: 20, color: "bg-blue-600" },
];

export const leadTrend = [34, 42, 38, 51, 47, 66, 74, 69, 83, 92, 88, 104];
